version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      time: "08:00"
    cooldown:
      default-days: 1
    target-branch: "main"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      time: "08:00"
