import react from "@vitejs/plugin-react";
import path from "node:path";
import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ignorePatterns: ["dist/"],
    jsdoc: true,
    sortImports: {
      customGroups: [
        {
          elementNamePattern: ["react", "react-dom"],
          groupName: "react",
        },
      ],
      groups: [
        "react",
        ["value-builtin", "value-external"],
        "value-internal",
        ["value-parent", "value-sibling", "value-index"],
        ["type-parent", "type-sibling", "type-index"],
        "type-internal",
        "type-import",
        "unknown",
      ],
      ignoreCase: true,
      internalPattern: ["#/"],
      newlinesBetween: true,
      order: "asc",
    },
    sortPackageJson: {
      sortScripts: true,
    },
  },
  lint: {
    categories: {
      nursery: "warn",
      pedantic: "warn",
      perf: "warn",
      restriction: "warn",
      style: "warn",
      suspicious: "warn",
    },
    env: {
      browser: true,
      node: true,
    },
    ignorePatterns: ["dist/"],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["*.config.ts"],
        rules: {
          "import/no-nodejs-modules": "off",
        },
      },
      {
        files: ["**/*.d.ts"],
        rules: {
          "import/unambiguous": "off",
        },
      },
    ],
    plugins: [
      "eslint",
      "typescript",
      "unicorn",
      "react",
      "react-perf",
      "oxc",
      "import",
      "jsx-a11y",
    ],
    rules: {
      complexity: "off",
      "func-style": ["error", "expression"],
      "id-length": "off",
      "import/consistent-type-specifier-style": "off",
      "import/exports-last": "off",
      "import/group-exports": "off",
      "import/max-dependencies": "off",
      "import/no-default-export": "off",
      "import/no-named-export": "off",
      "import/no-namespace": "off",
      "import/no-unassigned-import": "off",
      "import/prefer-default-export": "off",
      "max-lines": ["warn", { max: 500, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": "off",
      "max-statements": "off",
      "no-alert": "off",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-inline-comments": "off",
      "no-magic-numbers": "off",
      "no-nested-ternary": "off",
      "no-plusplus": "off",
      "no-ternary": "off",
      "no-undefined": "off",
      "oxc/no-async-await": "off",
      "oxc/no-barrel-file": "off",
      "oxc/no-optional-chaining": "off",
      "oxc/no-rest-spread-properties": "off",
      "react-perf/jsx-no-new-array-as-prop": "off",
      "react-perf/jsx-no-new-function-as-prop": "off",
      "react-perf/jsx-no-new-object-as-prop": "off",
      "react/jsx-filename-extension": ["warn", { extensions: [".tsx"] }],
      "react/jsx-max-depth": "off",
      "react/jsx-no-literals": "off",
      "react/jsx-no-useless-fragment": "off",
      "react/jsx-props-no-spreading": "off",
      "react/react-in-jsx-scope": "off",
      "sort-imports": "off",
      "sort-keys": "warn",
      "typescript/consistent-type-definitions": ["error", "type"],
      "typescript/explicit-function-return-type": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/no-empty-interface": "off",
      "typescript/no-non-null-assertion": "off",
      "typescript/no-unsafe-type-assertion": "off",
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/strict-boolean-expressions": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-null": "off",
      "unicorn/numeric-separators-style": "off",
      "unicorn/prefer-global-this": "off",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
  plugins: [react()],
  resolve: {
    alias: {
      "#": path.resolve(import.meta.dirname, "src"),
    },
  },
  test: {
    environment: "jsdom",
    globals: false,
    include: ["src/**/*.{spec,test}.{ts,tsx}"],
    setupFiles: ["./tests/vitest.setup.ts"],
  },
});
